spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  thymeleaf:
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
